package Entidades;
// Generated 07/04/2015 21:25:37 by Hibernate Tools 4.3.1



/**
 * Adm generated by hbm2java
 */
public class Adm  implements java.io.Serializable {


     private Integer idAdm;
     private String usuarioAdm;
     private String senhaAdm;

    public Adm() {
    }

    public Adm(String usuarioAdm, String senhaAdm) {
       this.usuarioAdm = usuarioAdm;
       this.senhaAdm = senhaAdm;
    }
   
    public Integer getIdAdm() {
        return this.idAdm;
    }
    
    public void setIdAdm(Integer idAdm) {
        this.idAdm = idAdm;
    }
    public String getUsuarioAdm() {
        return this.usuarioAdm;
    }
    
    public void setUsuarioAdm(String usuarioAdm) {
        this.usuarioAdm = usuarioAdm;
    }
    public String getSenhaAdm() {
        return this.senhaAdm;
    }
    
    public void setSenhaAdm(String senhaAdm) {
        this.senhaAdm = senhaAdm;
    }




}


