package Entidades;
// Generated 07/04/2015 21:25:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer codCliente;
     private String nomeCliente;
     private int cpfCnpjCliente;
     private String emailUsuario;
     private String senhaUsuario;
     private Set enderecoClientes = new HashSet(0);
     private Set vendas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String nomeCliente, int cpfCnpjCliente, String emailUsuario, String senhaUsuario) {
        this.nomeCliente = nomeCliente;
        this.cpfCnpjCliente = cpfCnpjCliente;
        this.emailUsuario = emailUsuario;
        this.senhaUsuario = senhaUsuario;
    }
    public Cliente(String nomeCliente, int cpfCnpjCliente, String emailUsuario, String senhaUsuario, Set enderecoClientes, Set vendas) {
       this.nomeCliente = nomeCliente;
       this.cpfCnpjCliente = cpfCnpjCliente;
       this.emailUsuario = emailUsuario;
       this.senhaUsuario = senhaUsuario;
       this.enderecoClientes = enderecoClientes;
       this.vendas = vendas;
    }
   
    public Integer getCodCliente() {
        return this.codCliente;
    }
    
    public void setCodCliente(Integer codCliente) {
        this.codCliente = codCliente;
    }
    public String getNomeCliente() {
        return this.nomeCliente;
    }
    
    public void setNomeCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }
    public int getCpfCnpjCliente() {
        return this.cpfCnpjCliente;
    }
    
    public void setCpfCnpjCliente(int cpfCnpjCliente) {
        this.cpfCnpjCliente = cpfCnpjCliente;
    }
    public String getEmailUsuario() {
        return this.emailUsuario;
    }
    
    public void setEmailUsuario(String emailUsuario) {
        this.emailUsuario = emailUsuario;
    }
    public String getSenhaUsuario() {
        return this.senhaUsuario;
    }
    
    public void setSenhaUsuario(String senhaUsuario) {
        this.senhaUsuario = senhaUsuario;
    }
    public Set getEnderecoClientes() {
        return this.enderecoClientes;
    }
    
    public void setEnderecoClientes(Set enderecoClientes) {
        this.enderecoClientes = enderecoClientes;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


