package Entidades;
// Generated 07/04/2015 21:25:37 by Hibernate Tools 4.3.1



/**
 * EnderecoClienteId generated by hbm2java
 */
public class EnderecoClienteId  implements java.io.Serializable {


     private int cep;
     private int clienteCodCliente;

    public EnderecoClienteId() {
    }

    public EnderecoClienteId(int cep, int clienteCodCliente) {
       this.cep = cep;
       this.clienteCodCliente = clienteCodCliente;
    }
   
    public int getCep() {
        return this.cep;
    }
    
    public void setCep(int cep) {
        this.cep = cep;
    }
    public int getClienteCodCliente() {
        return this.clienteCodCliente;
    }
    
    public void setClienteCodCliente(int clienteCodCliente) {
        this.clienteCodCliente = clienteCodCliente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EnderecoClienteId) ) return false;
		 EnderecoClienteId castOther = ( EnderecoClienteId ) other; 
         
		 return (this.getCep()==castOther.getCep())
 && (this.getClienteCodCliente()==castOther.getClienteCodCliente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCep();
         result = 37 * result + this.getClienteCodCliente();
         return result;
   }   


}


