package Entidades;
// Generated 07/04/2015 21:25:37 by Hibernate Tools 4.3.1



/**
 * ProdutoVenda generated by hbm2java
 */
public class ProdutoVenda  implements java.io.Serializable {


     private ProdutoVendaId id;
     private Produto produto;
     private Venda venda;

    public ProdutoVenda() {
    }

    public ProdutoVenda(ProdutoVendaId id, Produto produto, Venda venda) {
       this.id = id;
       this.produto = produto;
       this.venda = venda;
    }
   
    public ProdutoVendaId getId() {
        return this.id;
    }
    
    public void setId(ProdutoVendaId id) {
        this.id = id;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }




}


