package Entidades;
// Generated 07/04/2015 21:25:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer codProduto;
     private long precoProduto;
     private long precoVenda;
     private String statusProduto;
     private String nomeProduto;
     private int qtdProduto;
     private Set produtoVendas = new HashSet(0);

    public Produto() {
    }

	
    public Produto(long precoProduto, long precoVenda, String statusProduto, String nomeProduto, int qtdProduto) {
        this.precoProduto = precoProduto;
        this.precoVenda = precoVenda;
        this.statusProduto = statusProduto;
        this.nomeProduto = nomeProduto;
        this.qtdProduto = qtdProduto;
    }
    public Produto(long precoProduto, long precoVenda, String statusProduto, String nomeProduto, int qtdProduto, Set produtoVendas) {
       this.precoProduto = precoProduto;
       this.precoVenda = precoVenda;
       this.statusProduto = statusProduto;
       this.nomeProduto = nomeProduto;
       this.qtdProduto = qtdProduto;
       this.produtoVendas = produtoVendas;
    }
   
    public Integer getCodProduto() {
        return this.codProduto;
    }
    
    public void setCodProduto(Integer codProduto) {
        this.codProduto = codProduto;
    }
    public long getPrecoProduto() {
        return this.precoProduto;
    }
    
    public void setPrecoProduto(long precoProduto) {
        this.precoProduto = precoProduto;
    }
    public long getPrecoVenda() {
        return this.precoVenda;
    }
    
    public void setPrecoVenda(long precoVenda) {
        this.precoVenda = precoVenda;
    }
    public String getStatusProduto() {
        return this.statusProduto;
    }
    
    public void setStatusProduto(String statusProduto) {
        this.statusProduto = statusProduto;
    }
    public String getNomeProduto() {
        return this.nomeProduto;
    }
    
    public void setNomeProduto(String nomeProduto) {
        this.nomeProduto = nomeProduto;
    }
    public int getQtdProduto() {
        return this.qtdProduto;
    }
    
    public void setQtdProduto(int qtdProduto) {
        this.qtdProduto = qtdProduto;
    }
    public Set getProdutoVendas() {
        return this.produtoVendas;
    }
    
    public void setProdutoVendas(Set produtoVendas) {
        this.produtoVendas = produtoVendas;
    }




}


