package Entidades;
// Generated 07/04/2015 21:25:37 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private Integer codVenda;
     private Cliente cliente;
     private String statusVenda;
     private Date dataVenda;
     private BigDecimal totalVenda;
     private Set produtoVendas = new HashSet(0);

    public Venda() {
    }

	
    public Venda(Cliente cliente, String statusVenda, Date dataVenda, BigDecimal totalVenda) {
        this.cliente = cliente;
        this.statusVenda = statusVenda;
        this.dataVenda = dataVenda;
        this.totalVenda = totalVenda;
    }
    public Venda(Cliente cliente, String statusVenda, Date dataVenda, BigDecimal totalVenda, Set produtoVendas) {
       this.cliente = cliente;
       this.statusVenda = statusVenda;
       this.dataVenda = dataVenda;
       this.totalVenda = totalVenda;
       this.produtoVendas = produtoVendas;
    }
   
    public Integer getCodVenda() {
        return this.codVenda;
    }
    
    public void setCodVenda(Integer codVenda) {
        this.codVenda = codVenda;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getStatusVenda() {
        return this.statusVenda;
    }
    
    public void setStatusVenda(String statusVenda) {
        this.statusVenda = statusVenda;
    }
    public Date getDataVenda() {
        return this.dataVenda;
    }
    
    public void setDataVenda(Date dataVenda) {
        this.dataVenda = dataVenda;
    }
    public BigDecimal getTotalVenda() {
        return this.totalVenda;
    }
    
    public void setTotalVenda(BigDecimal totalVenda) {
        this.totalVenda = totalVenda;
    }
    public Set getProdutoVendas() {
        return this.produtoVendas;
    }
    
    public void setProdutoVendas(Set produtoVendas) {
        this.produtoVendas = produtoVendas;
    }




}


